// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Map: typeof import('./src/components/Map.vue')['default']
    Marker: typeof import('./src/components/Marker.vue')['default']
  }
}

export { }
